# Generated by Django 3.1.7 on 2021-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210310_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.ImageField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
